name: tempest-jhobbs
version: 0
summary: OpenStack tempest test
description: Tempest snap
confinement: strict

apps:
    tempest:
        command: usr/bin/tempest
        plugs: [
            network,      # tempest has to reach the openstack APIs.
            network-bind, # urllib3 tests binding to an IPv6 address.
        ]

parts:
    tempest:
        plugin: python2
        source: https://github.com/openstack/tempest.git
